// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtl45oyA5PtadLg3mUDqqNNGzwdbBSY_4',
    appId: '1:694812612533:web:50e97219f31be7cabdebfc',
    messagingSenderId: '694812612533',
    projectId: 'nibble-97e84',
    authDomain: 'nibble-97e84.firebaseapp.com',
    storageBucket: 'nibble-97e84.firebasestorage.app',
    measurementId: 'G-Z45N5ZF3XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_pd7fMAWq0HciHQ2M09zV3pyOIfbPj8w',
    appId: '1:694812612533:android:eb68b6e0361e695fbdebfc',
    messagingSenderId: '694812612533',
    projectId: 'nibble-97e84',
    storageBucket: 'nibble-97e84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4lQVxpjN8vCtQpV1MY_Sndl1e7PwUPrc',
    appId: '1:694812612533:ios:f709382c0b34e9dbbdebfc',
    messagingSenderId: '694812612533',
    projectId: 'nibble-97e84',
    storageBucket: 'nibble-97e84.firebasestorage.app',
    iosBundleId: 'com.example.nibbleApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4lQVxpjN8vCtQpV1MY_Sndl1e7PwUPrc',
    appId: '1:694812612533:ios:f709382c0b34e9dbbdebfc',
    messagingSenderId: '694812612533',
    projectId: 'nibble-97e84',
    storageBucket: 'nibble-97e84.firebasestorage.app',
    iosBundleId: 'com.example.nibbleApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtl45oyA5PtadLg3mUDqqNNGzwdbBSY_4',
    appId: '1:694812612533:web:50e97219f31be7cabdebfc',
    messagingSenderId: '694812612533',
    projectId: 'nibble-97e84',
    authDomain: 'nibble-97e84.firebaseapp.com',
    storageBucket: 'nibble-97e84.firebasestorage.app',
    measurementId: 'G-Z45N5ZF3XY',
  );
}
